name: Good Bye workflow

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  task-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo 'Goodbye World'
        shell: bash
    only:
      - merge_requests
